### ISSUE TITLE
Historical Marker Info Window User Story

### ISSUE THREAD

**Issue by matthamil** [NSSCodeForNashville/NashvilleHistory#25]
### User Story

GIVEN a user is on the main page with the map view
WHEN a user clicks on a historical marker icon on the map,
THEN the list of cards below the map is filtered to just show the historical marker selected
AND the card is expanded to show a full image (if available), description, action buttons for directions, bookmarking, adding to routes
THEN the marker on the map is emphasized(?)

**Comment by MattKraatz** [comment]
@delainewendling killed it on this one
