### ISSUE TITLE
Add Art Markers to the Places Near Me View

### ISSUE THREAD

**Issue by delaineackerman** [NSSCodeForNashville/NashvilleHistory#31]
### Feature Description

The application serves to connect users to historical AND art markers in Nashville. The application only shows Historical markers in the places near me view so art markers need to be added to that view.

### Recommended Actions

1. Get the art marker information from the Nashville Gov Art in Public Places and Metro Public Art APIs 
1. Print out the markers, regardless of type, in the order of closest to furthest away from the location of the user. 

### Related Issues/PRs

#23

**Comment by matthamil** [comment]
Did #32 resolve this?
